version: 2.1
jobs:
  upload_pdsdk_browser:
    docker:
      # XXX lol... just use node:10 with aws-cli installed on it
      - image: pipedreamhq/cci-build-k8s-java
    steps:
      - checkout
      - run:
          command: |
            aws s3 sync javascript/dist s3://sdk.pipedream.net/
workflows:
  version: 2
  default:
    jobs:
      - upload_pdsdk_browser:
          context: pipedream
          filters:
            branches:
              only:
                - master
