# TODO maybe build just in CI, gitignore dist, and create artifacts and link to those instead
name: upload_pdsdk_browser
on:
  push:
    branches:
      - master
    paths:
      - javascript/dist/*
      - .github/workflows/upload_pdsdk_browser.yml
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - env:
          AWS_ACCESS_KEY_ID: '${{ secrets.CIRCLE_USER_AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.CIRCLE_USER_AWS_SECRET_ACCESS_KEY }}'
          CLOUDFRONT_DISTRIBUTION_ID: '${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}'
        run: |
          aws s3 sync javascript/dist s3://sdk.pipedream.net/
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
